language: php
php:
  - 5.5
before_script:
  - cd testing
  - cat test
deploy:
  bucket: powerline-server-builds
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
