language: python
python:
  - "2.7"
cache: pip
install:
  - pip install requests
script:
  - python tests.py
deploy:
  bucket: powerline-server-builds
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
